server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  flyway:
    locations: classpath:db/migration
  application:
    name: algamoney-api
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5431/db_algamoney
    password: root
    hikari:
      maximum-pool-size: 25
      minimum-idle: 10
      idle-timeout: 10000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    format-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

secretKey: 1b2d7a2079285f016ee03c922440bdfaa6cdc31ab0e0a9f98c018b6528ae78d4
